CREATE DATABASE QuanLyBanHang;

USE QuanLyBanHang;

-- 1. Bảng Customer
CREATE TABLE Customer (
    cID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cName VARCHAR(50) NOT NULL,
    cAge INT
);

-- 2. Bảng Product
CREATE TABLE Product (
    pID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pName VARCHAR(100) NOT NULL,
    pPrice DECIMAL(12,2) NOT NULL
);

-- 3. Bảng Order
CREATE TABLE `Order` (
    oID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cID INT NOT NULL,
    oDate DATE NOT NULL,
    oTotalPrice DECIMAL(12,2) NOT NULL,

    FOREIGN KEY (cID) REFERENCES Customer(cID)
);

-- 4. Bảng OrderDetail
CREATE TABLE OrderDetail (
    oID INT NOT NULL,
    pID INT NOT NULL,
    odQTY INT NOT NULL,

    PRIMARY KEY (oID, pID),

    FOREIGN KEY (oID) REFERENCES `Order`(oID),
    FOREIGN KEY (pID) REFERENCES Product(pID)
);